#!/bin/sh
#find -E . -type f -regex '.*\.(cpp|h|c)' -not -name '*CMake*' -print0 | xargs -0t -n 1 clang-format -style=file -i
git ls-tree -r HEAD --name-only | grep -E ".*\.(hpp|cpp|h|c)$" | xargs -t -n 1 clang-format -style=file -i
